### ISSUE TITLE
Alternative Storage backends?

### ISSUE THREAD

**Issue by jaystary** [japila-books/delta-lake-internals#1]
Hi Jacek, 

thank you so much for this collection of the info. This is very useful.

We want to use delta lake for a larger project that will be on-prem, and we are evaluating if there is any viable (existing) alternative to HDFS that could be used that complies with the Delta storage requirements. I was wondering if you are aware of any, as so far i came up empty.

Thank you.

**Comment by jaceklaskowski** [comment]
Hey Jay,

> if there is any viable (existing) alternative to HDFS that could be used that complies with the Delta storage requirements.

I haven't heard of any myself either but I could ask around and see if I can find anything. Can you point me at the Delta storage requirements and what alternatives you're interested in?

**Comment by jaystary** [comment]
Hey Jacek,

we are open to what we use, however, we try to come up with a solution that minimizes the effort in regards to setup & maintenance.

Our setup is Kubernetes based thus what we access as storage should be Kubernetes managed (even in the case of HDFS).

The infrastructure we are going to use are multiple Nvidia DGX boxes that will act as the Kubernetes cluster that are connected via network, allowing to use the inbuilt NVMe storage as well as the available compute resources. Due to this set up we were considering MinIO or potentially CephFS as alternatives to HDFS.

**Comment by jaceklaskowski** [comment]
I've got no experience with such a setup so I personally can't help much. I'd recommend posting this question at https://stackoverflow.com/questions/tagged/delta-lake to reach out to the Delta Lake community.

**Comment by jaystary** [comment]
Thanks for the feedback, I will reach out to them!
